version: '3.8'

services:
  security-toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # API
      - "3000:3000"  # Frontend
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/security_toolbox
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    depends_on:
      - db
    networks:
      - security-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=security_toolbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - security-network

volumes:
  postgres_data:

networks:
  security-network:
    driver: bridge 